# Generated by Django 4.1.5 on 2023-01-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stdetails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="name",
            field=models.CharField(default="my name", max_length=30),
        ),
    ]
